In [1]:
import pandas as pd
import numpy as np

# ...없애기
# pd.options.display.max_columns = None
# pd.options.display.max_rows = None

In [2]:
df_a = pd.read_csv('./datasets/2015.csv')
for i in range(2016,2023):
    year = i
    df_b = pd.read_csv(f'./datasets/{year}.csv')
    df_a = pd.concat([df_a, df_b])
df_a

        시도  시군구 계약종별    년도   월        전력 사용량  Unnamed: 0
0    서울특별시  종로구  주택용  2015  1월  2.414819e+07         NaN
1    서울특별시  종로구  주택용  2015  2월  2.308385e+07         NaN
2    서울특별시  종로구  주택용  2015  3월  2.033165e+07         NaN
3    서울특별시  종로구  주택용  2015  4월  2.073120e+07         NaN
4    서울특별시  종로구  주택용  2015  5월  1.950405e+07         NaN
..     ...  ...  ...   ...  ..           ...         ...
512  울산광역시  울주군  교육용  2022  1월  9.139668e+06       512.0
513  울산광역시  울주군  산업용  2022  1월  1.030417e+09       513.0
514  울산광역시  울주군  농사용  2022  1월  6.842901e+06       514.0
515  울산광역시  울주군  가로등  2022  1월  2.703994e+06       515.0
516  울산광역시  울주군  심 야  2022  1월  6.547839e+06       516.0

[43921 rows x 7 columns]

In [3]:
df_a['월'] = df_a['월'].replace({'1월':'1', '2월':'2', '3월':'3', '4월':'4', '5월':'5', '6월':'6', 
                               '7월':'7', '8월':'8', '9월':'9', '10월':'10', '11월':'11', '12월':'12' })
df_a

        시도  시군구 계약종별    년도  월        전력 사용량  Unnamed: 0
0    서울특별시  종로구  주택용  2015  1  2.414819e+07         NaN
1    서울특별시  종로구  주택용  2015  2  2.308385e+07         NaN
2    서울특별시  종로구  주택용  2015  3  2.033165e+07         NaN
3    서울특별시  종로구  주택용  2015  4  2.073120e+07         NaN
4    서울특별시  종로구  주택용  2015  5  1.950405e+07         NaN
..     ...  ...  ...   ... ..           ...         ...
512  울산광역시  울주군  교육용  2022  1  9.139668e+06       512.0
513  울산광역시  울주군  산업용  2022  1  1.030417e+09       513.0
514  울산광역시  울주군  농사용  2022  1  6.842901e+06       514.0
515  울산광역시  울주군  가로등  2022  1  2.703994e+06       515.0
516  울산광역시  울주군  심 야  2022  1  6.547839e+06       516.0

[43921 rows x 7 columns]

In [10]:
df = df_a.iloc[:, :-1]
df

        시도  시군구 계약종별    년도  월        전력 사용량
0    서울특별시  종로구  주택용  2015  1  2.414819e+07
1    서울특별시  종로구  주택용  2015  2  2.308385e+07
2    서울특별시  종로구  주택용  2015  3  2.033165e+07
3    서울특별시  종로구  주택용  2015  4  2.073120e+07
4    서울특별시  종로구  주택용  2015  5  1.950405e+07
..     ...  ...  ...   ... ..           ...
512  울산광역시  울주군  교육용  2022  1  9.139668e+06
513  울산광역시  울주군  산업용  2022  1  1.030417e+09
514  울산광역시  울주군  농사용  2022  1  6.842901e+06
515  울산광역시  울주군  가로등  2022  1  2.703994e+06
516  울산광역시  울주군  심 야  2022  1  6.547839e+06

[43921 rows x 6 columns]

In [13]:
df.to_csv("15~22년월별전력량.csv", index=False)